spring:
    application:
        name: jblog
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/jblog
        username: sandro
        password: San245654
    jpa:
        hibernate:
            ddl-auto: update
        database: postgresql
